// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var webstreamer = webstreamer || {};

/**
 * @const
 * @namespace
 */
webstreamer.livestreamer = webstreamer.livestreamer || {};

/**
 * @constructor
 */
webstreamer.livestreamer.Create = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {webstreamer.livestreamer.Create}
 */
webstreamer.livestreamer.Create.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {webstreamer.livestreamer.Create=} obj
 * @returns {webstreamer.livestreamer.Create}
 */
webstreamer.livestreamer.Create.getRootAsCreate = function(bb, obj) {
  return (obj || new webstreamer.livestreamer.Create).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
webstreamer.livestreamer.Create.prototype.name = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {webstreamer.Endpoint=} obj
 * @returns {webstreamer.Endpoint|null}
 */
webstreamer.livestreamer.Create.prototype.source = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new webstreamer.Endpoint).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
webstreamer.livestreamer.Create.startCreate = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} nameOffset
 */
webstreamer.livestreamer.Create.addName = function(builder, nameOffset) {
  builder.addFieldOffset(0, nameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} sourceOffset
 */
webstreamer.livestreamer.Create.addSource = function(builder, sourceOffset) {
  builder.addFieldOffset(1, sourceOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
webstreamer.livestreamer.Create.endCreate = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
webstreamer.livestreamer.Destroy = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {webstreamer.livestreamer.Destroy}
 */
webstreamer.livestreamer.Destroy.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {webstreamer.livestreamer.Destroy=} obj
 * @returns {webstreamer.livestreamer.Destroy}
 */
webstreamer.livestreamer.Destroy.getRootAsDestroy = function(bb, obj) {
  return (obj || new webstreamer.livestreamer.Destroy).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
webstreamer.livestreamer.Destroy.prototype.name = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
webstreamer.livestreamer.Destroy.startDestroy = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} nameOffset
 */
webstreamer.livestreamer.Destroy.addName = function(builder, nameOffset) {
  builder.addFieldOffset(0, nameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
webstreamer.livestreamer.Destroy.endDestroy = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
webstreamer.livestreamer.AddViewer = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {webstreamer.livestreamer.AddViewer}
 */
webstreamer.livestreamer.AddViewer.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {webstreamer.livestreamer.AddViewer=} obj
 * @returns {webstreamer.livestreamer.AddViewer}
 */
webstreamer.livestreamer.AddViewer.getRootAsAddViewer = function(bb, obj) {
  return (obj || new webstreamer.livestreamer.AddViewer).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
webstreamer.livestreamer.AddViewer.prototype.component = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {webstreamer.Endpoint=} obj
 * @returns {webstreamer.Endpoint|null}
 */
webstreamer.livestreamer.AddViewer.prototype.viewer = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new webstreamer.Endpoint).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
webstreamer.livestreamer.AddViewer.startAddViewer = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} componentOffset
 */
webstreamer.livestreamer.AddViewer.addComponent = function(builder, componentOffset) {
  builder.addFieldOffset(0, componentOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} viewerOffset
 */
webstreamer.livestreamer.AddViewer.addViewer = function(builder, viewerOffset) {
  builder.addFieldOffset(1, viewerOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
webstreamer.livestreamer.AddViewer.endAddViewer = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
webstreamer.livestreamer.RemoveViewer = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {webstreamer.livestreamer.RemoveViewer}
 */
webstreamer.livestreamer.RemoveViewer.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {webstreamer.livestreamer.RemoveViewer=} obj
 * @returns {webstreamer.livestreamer.RemoveViewer}
 */
webstreamer.livestreamer.RemoveViewer.getRootAsRemoveViewer = function(bb, obj) {
  return (obj || new webstreamer.livestreamer.RemoveViewer).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
webstreamer.livestreamer.RemoveViewer.prototype.component = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
webstreamer.livestreamer.RemoveViewer.prototype.endpoint = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
webstreamer.livestreamer.RemoveViewer.startRemoveViewer = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} componentOffset
 */
webstreamer.livestreamer.RemoveViewer.addComponent = function(builder, componentOffset) {
  builder.addFieldOffset(0, componentOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} endpointOffset
 */
webstreamer.livestreamer.RemoveViewer.addEndpoint = function(builder, endpointOffset) {
  builder.addFieldOffset(1, endpointOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
webstreamer.livestreamer.RemoveViewer.endRemoveViewer = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
webstreamer.livestreamer.LiveStreamError = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {webstreamer.livestreamer.LiveStreamError}
 */
webstreamer.livestreamer.LiveStreamError.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {webstreamer.livestreamer.LiveStreamError=} obj
 * @returns {webstreamer.livestreamer.LiveStreamError}
 */
webstreamer.livestreamer.LiveStreamError.getRootAsLiveStreamError = function(bb, obj) {
  return (obj || new webstreamer.livestreamer.LiveStreamError).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
webstreamer.livestreamer.LiveStreamError.prototype.code = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readInt16(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
webstreamer.livestreamer.LiveStreamError.prototype.reason = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
webstreamer.livestreamer.LiveStreamError.startLiveStreamError = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} code
 */
webstreamer.livestreamer.LiveStreamError.addCode = function(builder, code) {
  builder.addFieldInt16(0, code, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} reasonOffset
 */
webstreamer.livestreamer.LiveStreamError.addReason = function(builder, reasonOffset) {
  builder.addFieldOffset(1, reasonOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
webstreamer.livestreamer.LiveStreamError.endLiveStreamError = function(builder) {
  var offset = builder.endObject();
  return offset;
};

// Exports for Node.js and RequireJS
this.webstreamer = webstreamer;
